/* SPDX-License-Identifier: MIT */
#ifndef OVERLAY_FS_H
#define OVERLAY_FS_H

#include <sqlite3.h>
#include <stddef.h>
#include <stdint.h>

/*
 * Versioned file system using SQLite
 *
 * Features:
 * - All file writes create new versions (immutable history)
 * - Fast reads using indexed queries
 * - Single SQLite database, no external dependencies
 */

/*
 * Initialize overlay_fs database
 *
 * Opens or creates the database and applies schema.
 * If embedded fs.db exists, migrates SQLAR data to file_versions.
 *
 * @param db_path: Path to database file (or ":memory:" for in-memory)
 * @param db: Output parameter for database handle
 * @return 0 on success, -1 on error
 */
int overlay_fs_init(const char *db_path, sqlite3 **db);

/*
 * Check that overlay_fs schema exists
 *
 * Verifies that required tables (file_versions, file_ids) are present.
 * This should be called after database initialization to ensure the
 * schema was applied at build time.
 *
 * @param db: Database handle
 * @return 0 on success, -1 on error (missing schema)
 */
int overlay_fs_check_schema(sqlite3 *db);

/*
 * Migrate SQLAR archive to file_versions table
 *
 * Reads all entries from sqlar table, decompresses them,
 * and inserts as version 1 in file_versions.
 * Drops sqlar table afterward and vacuums database.
 *
 * @param db: Database handle
 * @return 0 on success, -1 on error
 */
int overlay_fs_migrate_sqlar(sqlite3 *db);

/*
 * Migration status codes for asset bundle migration
 */
typedef enum {
	MIGRATE_OK = 0,
	MIGRATE_ERR_DECOMPRESS = -1,
	MIGRATE_ERR_DB = -2,
	MIGRATE_ERR_ALREADY_APPLIED = -3,
	MIGRATE_ERR_CORRUPT = -4,
} migrate_status_t;

/*
 * Migrate asset bundle to file_versions table
 *
 * Takes a compressed asset bundle (generated by asset_packer), decompresses it,
 * parses the binary format, and inserts all entries as version 1 in file_versions.
 * Migration is idempotent: subsequent calls with the same bundle are no-ops.
 *
 * Binary format (after decompression):
 *   [num_entries:u32]
 *   repeat num_entries times:
 *     [name_len:u32]
 *     [name:bytes]
 *     [data_len:u32]
 *     [data:bytes]
 *
 * @param db: Database handle
 * @param bundle_blob: Compressed bundle data (from asset_packer)
 * @param bundle_len: Length of compressed bundle
 * @return migrate_status_t status code
 */
migrate_status_t overlay_fs_migrate_assets(
	sqlite3 *db,
	const uint8_t *bundle_blob,
	size_t bundle_len
);

/*
 * Read latest version of a file
 *
 * Uses optimized query with file_id and MAX(version_number).
 *
 * @param db: Database handle
 * @param path: File path
 * @param data: Output parameter for file data (caller must free)
 * @param size: Output parameter for file size
 * @return 0 on success, -1 on error (file not found or SQL error)
 */
int overlay_fs_read(sqlite3 *db, const char *path,
                    unsigned char **data, size_t *size);

/*
 * Write new version of a file
 *
 * Creates new version entry with incremented version_number.
 * If file doesn't exist, creates new file_id.
 *
 * @param db: Database handle
 * @param path: File path
 * @param data: File data
 * @param size: File size
 * @return 0 on success, -1 on error
 */
int overlay_fs_write(sqlite3 *db, const char *path,
                     const unsigned char *data, size_t size);

/*
 * Check if file exists
 *
 * @param db: Database handle
 * @param path: File path
 * @return 1 if exists, 0 if not found, -1 on error
 */
int overlay_fs_exists(sqlite3 *db, const char *path);

/*
 * Get file version count
 *
 * @param db: Database handle
 * @param path: File path
 * @return Version count (>= 1), 0 if not found, -1 on error
 */
int overlay_fs_version_count(sqlite3 *db, const char *path);

/*
 * Close database handle
 *
 * @param db: Database handle
 */
void overlay_fs_close(sqlite3 *db);

/*
 * Initialize global overlay_fs database handle
 *
 * Sets the internal database handle for file operations.
 * Must be called before using overlay_fs_read_file or overlay_fs_write_file.
 *
 * @param db: Database handle to use for all filesystem operations
 */
void overlay_fs_init_global(sqlite3 *db);

/*
 * Read file with overlay support
 *
 * Reads from the global database handle set by overlay_fs_init_global.
 * Uses latest_files view (overlay + base) for file access.
 * NO MUTEX - relies on SQLite's internal locking (SQLITE_THREADSAFE=1 + WAL).
 *
 * @param path: File path (e.g., "static/index.html" or "hbf/server.js")
 * @param enable_overlay: If 1, read from overlay; if 0, read from base only
 * @param data: Output parameter for file data (caller must free)
 * @param size: Output parameter for file size
 * @return 0 on success, -1 on error (file not found or SQL error)
 */
int overlay_fs_read_file(const char *path, int dev,
                         unsigned char **data, size_t *size);

/*
 * Write file to versioned filesystem
 *
 * Writes to the global database handle set by overlay_fs_init_global.
 * Creates new version entry with incremented version_number.
 * NO MUTEX - relies on SQLite's internal locking (SQLITE_THREADSAFE=1 + WAL).
 *
 * @param path: File path
 * @param data: File data
 * @param size: File size
 * @return 0 on success, -1 on error
 */
int overlay_fs_write_file(const char *path,
                          const unsigned char *data, size_t size);

#endif /* OVERLAY_FS_H */
