entryPoints:
  web:
    address: ":9080"

api:
  dashboard: true
  insecure: true

ping: {}

providers:
  file:
    filename: /tmp/traefik-dynamic.yml
    watch: true

log:
  level: INFO

global:
  checkNewVersion: false
  sendAnonymousUsage: false