// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTerminalOutput() {
  return window['go']['main']['App']['GetTerminalOutput']();
}

export function GetWebSocketURL() {
  return window['go']['main']['App']['GetWebSocketURL']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsTerminalRunning() {
  return window['go']['main']['App']['IsTerminalRunning']();
}

export function ResizeTerminal(arg1, arg2) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2);
}

export function SendTerminalInput(arg1) {
  return window['go']['main']['App']['SendTerminalInput'](arg1);
}

export function StartTerminal() {
  return window['go']['main']['App']['StartTerminal']();
}

export function StopTerminal() {
  return window['go']['main']['App']['StopTerminal']();
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}
