// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTerminalOutput():Promise<Record<string, any>>;

export function GetWebSocketURL():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function IsTerminalRunning():Promise<boolean>;

export function ResizeTerminal(arg1:number,arg2:number):Promise<Record<string, any>>;

export function SendTerminalInput(arg1:string):Promise<Record<string, any>>;

export function StartTerminal():Promise<Record<string, any>>;

export function StopTerminal():Promise<Record<string, any>>;

export function TestConnection():Promise<string>;
