#!/bin/bash
# inject_content.sh - Convert static files to SQL INSERT statements
#
# Usage: inject_content.sh <static_dir> <output_sql>
#
# Walks through static directory and generates SQL INSERT statements
# that add files to the nodes table with type='static' or 'script'.

set -e

if [ $# -ne 2 ]; then
	echo "Usage: $0 <static_dir> <output_sql>" >&2
	exit 1
fi

STATIC_DIR="$1"
OUTPUT_SQL="$2"

if [ ! -d "$STATIC_DIR" ]; then
	echo "Error: Directory '$STATIC_DIR' not found" >&2
	exit 1
fi

# Start SQL file
cat > "$OUTPUT_SQL" << 'EOF'
-- Static content for HBF
-- Generated by tools/inject_content.sh
-- DO NOT EDIT MANUALLY

EOF

# Process each file
find "$STATIC_DIR" -type f | sort | while read -r file; do
	# Get relative path from static dir
	rel_path="${file#$STATIC_DIR/}"

	# Determine type based on extension
	if [[ "$rel_path" == *.js ]]; then
		type="script"
	else
		type="static"
	fi

	# Extract just filename for server.js
	if [[ "$rel_path" == "server.js" ]]; then
		name="server.js"
	else
		name="/$rel_path"
	fi

	# Read file content and escape for JSON
	content=$(cat "$file" | python3 -c 'import sys, json; print(json.dumps(sys.stdin.read()))')

	# Generate INSERT statement
	cat >> "$OUTPUT_SQL" << EOF
INSERT INTO nodes (type, body) VALUES (
    '$type',
    json_object('name', '$name', 'content', $content)
);

EOF
done

echo "Generated $OUTPUT_SQL with $(grep -c '^INSERT' "$OUTPUT_SQL") inserts"
